apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackerui
spec:
  selector:
    matchLabels:
      app: trackerui
  template:
    metadata:
      labels:
        app: trackerui
    spec:
      containers:
      - name: trackerui
        image: sakthisaran/tracker_ui:BUILDNUMBER
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
